package UAS;

/*
Nama : La ode ian
Nim  : 3420210002
Prodi: Teknik Informatika
*/
 
public class UASLaode1 extends javax.swing.JFrame {

    /**
     * Creates new form UASLaode
     */
    public UASLaode1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SausPdg = new javax.swing.JRadioButton();
        GulaiNgk = new javax.swing.JRadioButton();
        hrgKuah = new javax.swing.JLabel();
        makanan = new javax.swing.JComboBox<>();
        Makanan = new javax.swing.JLabel();
        MenuMinuman = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Minuman = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        hitung = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        hrgmakanan = new javax.swing.JTextField();
        hrgminuman = new javax.swing.JTextField();
        TotalByr = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Rumah Makan Legendaris Italia Padang ");

        SausPdg.setText("Saus Padang");

        GulaiNgk.setText("Gulai Nangka");

        hrgKuah.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        hrgKuah.setText("Pilihan Kuah");

        makanan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        makanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fettuccine Alfredo Saus Padang", "Fettuccino Alfredo Gulai Nangka", "Lasagna Gulai Nangka", "Lasagna Saus Padang", "Pasta Primavera Saus Padang", "Pasta Primavera Gulai Nangka", "Spaghetti Gulai Nangka ", "Spaghetti Saus Padang" }));

        Makanan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Makanan.setText("Menu Makanan");

        MenuMinuman.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        MenuMinuman.setText("Minuman");

        Minuman.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Minuman.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Es Teh Janji Manis", "Kopi Hitam Kelam", "Susu Kambing", "Jus Ubi Madu" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(Minuman);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Perhitungan");

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Harga Makanan");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Harga Minuman");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Total Bayar");

        jLabel21.setText("<html><b>Daftar Harga Makanan</b><br>Fettuccine Alfredo Saus Padang Rp.50.000<br>Fettuccine Alfredo Gulai Nangka Rp.55.000<br>Lasagna Gulai Nangka Rp.60.000<br>Lasagna Saus Padang Rp.66.000<br>Pasta Primavera Saus Padang Rp.70.000<br>Pasta Primavera Gulai Nangka Rp.77.000<br>Spaghetti Gulai Nangka Rp.80.000<br>Spaghetti Saus Padang Rp.88.000<br><br><b>Daftar Harga Minuman</b><br>Es Teh Janji Manis Rp.10.000<br>Kopi Hitam Kelam Rp.15.000<br>Susu Kambing Rp.20.000<br>Jus Ubi Madu Rp.25.000</html>");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("La ode ian  3420210002");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Makanan)
                    .addComponent(hrgKuah)
                    .addComponent(MenuMinuman)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GulaiNgk)
                    .addComponent(SausPdg)
                    .addComponent(TotalByr, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrgmakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrgminuman, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makanan, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel1)
                .addGap(85, 85, 85)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hrgKuah)
                            .addComponent(SausPdg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GulaiNgk)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Makanan)
                            .addComponent(makanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MenuMinuman)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(hitung))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(hrgmakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(hrgminuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TotalByr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        double hargaMakanan = 0;
        double hargaMinuman = 0;
        double hargaKuah = 0;

        String selectedMenuMakanan = (String) makanan.getSelectedItem();
        if (selectedMenuMakanan != null) {
            switch (selectedMenuMakanan) {
                case "Fettuccine Alfredo Saus Padang":
                    hargaMakanan = 50000;
                    break;
                case "Fettuccine Alfredo Gulai Nangka":
                    hargaMakanan = 55000;
                    break;
                case "Lasagna Gulai Nangka":
                    hargaMakanan = 60000;
                    break;
                case "Lasagna Saus Padang":
                    hargaMakanan = 66000;
                    break;
                case "Pasta Primavera Saus Padang":
                    hargaMakanan = 70000;
                    break;
                case "Pasta Primavera Gulai Nangka":
                    hargaMakanan = 77000;
                    break;
                case "Spaghetti Gulia Nangka":
                    hargaMakanan = 80000;
                    break;
                case "Spaghetti Saus Padang":
                    hargaMakanan = 88000;
                    break;  
            }
        }

        String selectedMenuMinuman = Minuman.getSelectedValue();
        if (selectedMenuMinuman != null) {
            switch (selectedMenuMinuman) {
                case "Es Teh Janji Manis":
                    hargaMinuman = 10000;
                    break;
                case "Kopi Hitam Kelam":
                    hargaMinuman = 15000;
                    break;
                case "Susu Kambing":
                    hargaMinuman = 20000;
                    break;
                case "Jus Ubi Madu":
                    hargaMinuman = 25000;
                    break;
            }
        }
        if (SausPdg.isSelected()) {
            hargaKuah = 2000;
        } else if (GulaiNgk.isSelected()) {
            hargaKuah = 2000;
        }

        hrgmakanan.setText(String.valueOf(hargaMakanan));
        hrgminuman.setText(String.valueOf(hargaMinuman));
        hrgKuah.setText(String.valueOf(hargaKuah));

        double TotalHarga = hargaMakanan + hargaMinuman + hargaKuah;
        TotalByr.setText(String.valueOf(TotalHarga));
    }//GEN-LAST:event_hitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UASLaode1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UASLaode1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UASLaode1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UASLaode1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UASLaode1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton GulaiNgk;
    private javax.swing.JLabel Makanan;
    private javax.swing.JLabel MenuMinuman;
    private javax.swing.JList<String> Minuman;
    private javax.swing.JRadioButton SausPdg;
    private javax.swing.JTextField TotalByr;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel hrgKuah;
    private javax.swing.JTextField hrgmakanan;
    private javax.swing.JTextField hrgminuman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> makanan;
    // End of variables declaration//GEN-END:variables
}
