package UAS;

/*
Nama  : La ode ian
NIM   : 3420210002
Prodi : Teknik Informatika
*/

import LatihanJava.UAS;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

public class UASLaode2 extends javax.swing.JFrame {
    
    private final String Db_Username = "root";
    private final String Db_Password = "";
    private final String Db_Koneksi = "jdbc:mysql://localhost:3306/masterpelanggan";
    
    public UASLaode2() {
        initComponents();
        Atur_Combo();
        Bersih();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_JK = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kde = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cari = new javax.swing.JButton();
        nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pria = new javax.swing.JRadioButton();
        wanita = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        tlp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        save = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(16, 16, 16));
        jLabel9.setText("La ode ian  3420210002");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        jLabel3.setText("Kode Pelanggan");

        kde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        jLabel4.setText("Nama Pelanggan");

        cari.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        pria.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        pria.setText("Pria");

        wanita.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        wanita.setText("Wanita");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        jLabel6.setText("Alamat");

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        jLabel7.setText("Telepon");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        jLabel8.setText("Status");

        status.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N

        add.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(16, 16, 16));
        jLabel10.setText("Data Master Pelanggan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(add)
                                .addGap(18, 18, 18)
                                .addComponent(save)
                                .addGap(18, 18, 18)
                                .addComponent(update)
                                .addGap(18, 18, 18)
                                .addComponent(delete)
                                .addGap(18, 18, 18)
                                .addComponent(exit))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(jLabel4))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tlp, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(kde, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cari))
                                        .addComponent(nama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5)
                        .addGap(38, 38, 38)
                        .addComponent(pria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wanita))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cari))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pria)
                        .addComponent(wanita)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(save)
                                    .addComponent(add)
                                    .addComponent(update)
                                    .addComponent(delete)
                                    .addComponent(exit)))
                            .addComponent(jLabel7)))
                    .addComponent(jLabel6))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
       
        if(Cek_Kode() == false){
            return;
        }
        try{
            String Kode_Pelanggan = kde.getText().trim();
            String SQL = "SELECT * FROM pelanggan WHERE kdpel = '" + Kode_Pelanggan + "'";
            Connection Conn = (Connection) DriverManager.getConnection(Db_Koneksi,
                    Db_Username,Db_Password);
            Statement Stmt = Conn.createStatement();
            ResultSet RS = Stmt.executeQuery(SQL);
            if(!RS.next()){
                JOptionPane.showMessageDialog(rootPane, "Kode Pelanggan tidak ditemukan!",
                    "Informasi", JOptionPane.INFORMATION_MESSAGE);
                kde.setText("");
                kde.requestFocus();
                return;
            }
            JOptionPane.showMessageDialog(rootPane, "Kode Pelanggan ditemukan!",
                    "Informasi", JOptionPane.INFORMATION_MESSAGE);
            nama.setText(RS.getString("pel_nama"));
            if(RS.getString("pel_jk").equals("1")){
                pria.setSelected(true);
            }else{
                wanita.setSelected(true);
            }
            alamat.setText(RS.getString("pel_alamat"));
            tlp.setText(RS.getString("pel_telp"));
            status.setSelectedItem(RS.getString("pel_kawin"));
            Stmt.close();
            Conn.close();
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_cariActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
         Bersih();
    }//GEN-LAST:event_addActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        
        if(Cek_Kode() == false){
            return;
        }
         try{
            String SQL;
            Connection Conn;
            Statement Stmt;
            ResultSet RS;
            Conn = (Connection) DriverManager.getConnection(Db_Koneksi,
                    Db_Username,Db_Password);
            String Kode_Pelanggan = kde.getText();
            String Nama_Pelanggan = nama.getText();
            String Jenis_Kelamin;
            if(pria.isSelected()){
                Jenis_Kelamin = "1";
            }else{
                Jenis_Kelamin = "0";
            }
            String Alamat = alamat.getText();
            String Telepon = tlp.getText();
            String Status;
            if(status.getSelectedItem() == "Sudah Menikah"){
                Status = "1";
            }else if(status.getSelectedItem() == "Belum Menikah"){
                Status = "2";
            }else{
                Status = "0";
            }
            Calendar Cal = Calendar.getInstance();
            SimpleDateFormat SDF = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String TanggalJam = SDF.format(Cal.getTime());
            SQL = "SELECT * FROM pelanggan WHERE kdpel = '" + Kode_Pelanggan + "'";        
            Stmt = Conn.createStatement();
            RS = Stmt.executeQuery(SQL);
            RS.close();
            SQL = "INSERT INTO pelanggan (";
            SQL += "kdpel,";
            SQL += "pel_nama,";
            SQL += "pel_jk,";
            SQL += "pel_alamat,";
            SQL += "pel_telp,";
            SQL += "pel_kawin,";
            SQL += "pel_create,";
            SQL += "pel_update";
            SQL += ") VALUES (";
            SQL += "'" + Kode_Pelanggan + "',";
            SQL += "'" + Nama_Pelanggan + "',";
            SQL += "'" + Jenis_Kelamin + "',";
            SQL += "'" + Alamat + "',";
            SQL += "'" + Telepon + "',";
            SQL += "'" + Status + "',";
            SQL += "'" + TanggalJam + "',";
            SQL += "'" + TanggalJam + "'";
            SQL += ")";
            Stmt = Conn.createStatement();
            Stmt.executeUpdate(SQL);
            Stmt.close();
            Conn.close();
            JOptionPane.showMessageDialog(rootPane,"Input Data Berhasil."
                        ,"Informasi",JOptionPane.INFORMATION_MESSAGE);
            kde.requestFocus();
        }catch (SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        
        if(Cek_Kode() == false){
            return;
        }
        try{
            String Kode_Pelanggan = kde.getText();
            String Nama_Pelanggan = nama.getText();
            String Jenis_Kelamin;
            if(pria.isSelected()){
                Jenis_Kelamin = "1";
            }else{
                Jenis_Kelamin = "0";
            }
            String Alamat = alamat.getText();
            String Telepon = tlp.getText();
            String Status;
            if(status.getSelectedItem() == "Menikah"){
                Status = "1";
            }else if(status.getSelectedItem() == "Belum Menikah"){
                Status = "2";
            }else{
                Status = "0";
            }
            Calendar Cal = Calendar.getInstance();
            SimpleDateFormat SDF = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String TanggalJam = SDF.format(Cal.getTime());
            //==================SQL UPDATE=================//
            String SQL = "UPDATE pelanggan SET ";
            SQL += "pel_nama = '" + Nama_Pelanggan + "', ";
            SQL += "pel_jk = '" + Jenis_Kelamin + "', ";
            SQL += "pel_alamat = '" + Alamat + "', ";
            SQL += "pel_telp = '" + Telepon + "', ";
            SQL += "pel_kawin = '" + Status + "', ";
            SQL += "pel_update = '" + TanggalJam + "' ";
            SQL += "WHERE kdpel = '" + Kode_Pelanggan + "'";
            Connection Conn = (Connection) DriverManager.getConnection(Db_Koneksi,
                    Db_Username,Db_Password);
            Statement Stmt = Conn.createStatement();
            Stmt.executeUpdate(SQL);
            Stmt.close();
            Conn.close();
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil diUpdate!",
                    "Informasi", JOptionPane.INFORMATION_MESSAGE);
            Bersih();
            kde.requestFocus();
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        
        if(Cek_Kode() == false){
            return;
        }
        int Konfirmasi = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus?",
                "Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(Konfirmasi == 0){
            try{
                String SQL = "DELETE FROM pelanggan WHERE kdpel = ?";
                Connection Conn = (Connection) DriverManager.getConnection(Db_Koneksi,
                    Db_Username,Db_Password);
                PreparedStatement pst = Conn.prepareStatement(SQL);
                pst.setString(1, kde.getText());
                pst.executeUpdate();
                Conn.close();
                JOptionPane.showMessageDialog(rootPane, "Data Berhasil diDelete!",
                    "Informasi", JOptionPane.INFORMATION_MESSAGE);
                Bersih();
                kde.requestFocus();
            }catch(SQLException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        
        int Konfirmasi = JOptionPane.showConfirmDialog(null,"Yakin Ingin Keluar?",
                "Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (Konfirmasi == JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_exitActionPerformed

    private void kdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kdeActionPerformed

    private void Atur_Combo() {
        
        status.removeAllItems();
        status.addItem("Belum Menikah");
        status.addItem("Sudah Menikah ");
        status.addItem("Janda/Duda");
    }

    private void Bersih() {
        
        kde.setText("");
        nama.setText("");
        buttonGroup_JK.clearSelection();
        alamat.setText("");
        tlp.setText("");
        status.setSelectedIndex(0);
    }

    private boolean Cek_Kode() {
        
        boolean Cek = true;
        String Kode_Pelanggan = kde.getText().trim();
        if(Kode_Pelanggan.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Kode Pelanggan tidak boleh kosong.",
                    "Informasi", JOptionPane.INFORMATION_MESSAGE);
            kde.requestFocus();
            Cek = false;
        }
        return Cek;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UASLaode2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextArea alamat;
    private javax.swing.ButtonGroup buttonGroup_JK;
    private javax.swing.JButton cari;
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kde;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton pria;
    private javax.swing.JButton save;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTextField tlp;
    private javax.swing.JButton update;
    private javax.swing.JRadioButton wanita;
    // End of variables declaration//GEN-END:variables
}
